// <auto-generated />
using System;
using HRSTAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRSTAPI.Migrations
{
    [DbContext(typeof(HrstContext))]
    [Migration("20250901120832_BehevioralRiskDropped2")]
    partial class BehevioralRiskDropped2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRSTAPI.Models.HrstDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("BehavioralRisk")
                        .HasColumnType("int");

                    b.Property<string>("BehavioralRiskOther")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClinicalSign")
                        .HasColumnType("int");

                    b.Property<int>("ClinicalSignType")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EligibleForTesting")
                        .HasColumnType("int");

                    b.Property<int>("EscortedForLinkage")
                        .HasColumnType("int");

                    b.Property<bool>("ExchangedSexForMoney")
                        .HasColumnType("bit");

                    b.Property<int>("HIVTestResult")
                        .HasColumnType("int");

                    b.Property<bool>("HistoryofSexualViolence")
                        .HasColumnType("bit");

                    b.Property<int>("KnownHIVPositive")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("MultipleSexualPartners")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedleSharingforInjection")
                        .HasColumnType("bit");

                    b.Property<bool>("OtherBehavioralRiks")
                        .HasColumnType("bit");

                    b.Property<bool>("PartnerofKnownHIVPositive")
                        .HasColumnType("bit");

                    b.Property<int>("PatientGroup")
                        .HasColumnType("int");

                    b.Property<string>("PatientGroupOther")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PatientOnART")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ReceivedHIVTestSameDate")
                        .HasColumnType("int");

                    b.Property<string>("ReceivedHIVTestSameDateOther")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("STIHistory")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScreenedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.Property<bool>("SexWithNonRegularPartner")
                        .HasColumnType("bit");

                    b.Property<bool>("SexualPracticeUnderInfluence")
                        .HasColumnType("bit");

                    b.Property<bool>("UnprotectedSex")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("HrstDetails");
                });

            modelBuilder.Entity("HRSTAPI.Models.LookUp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("LookUps");
                });
#pragma warning restore 612, 618
        }
    }
}
